apiVersion: v1
kind: Service
metadata:
  name: django-test-api
  labels:
    app: django-test-api
spec:
  type: NodePort
  selector:
    app: django-test-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30211
---
apiVersion: v1
kind: Service
metadata:
  name: django-postgres-dep-service
  labels:
    app: django-postgres-dep-service
spec:
  type: ClusterIP
  selector:
    app: django-postgres-dep
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432