version: "3.3"

services:
  django:
    build: ./compose/local/Dockerfile
    image: usersapi:latest
    restart: "no"
    command: "python manage.py test"
    #command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - django-postgres-dep-service
    volumes:
      - .:/code
    env_file:
      - ./.envs/.local/.postgresql
    ports:
      - "8000:8000"

  django-postgres-dep-service:
    build: ./compose/local/postgres/Dockerfile
    image: postgres_sql:latest
    restart: "no"
    env_file:
      - ./.envs/.local/.postgresql